# Generated by Django 5.1.3 on 2024-11-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ata_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "attendant_name",
                    models.CharField(default="Não encontrado", max_length=100),
                ),
                (
                    "payment_method",
                    models.CharField(default="Não encontrado", max_length=100),
                ),
                ("effected", models.BooleanField()),
                ("audio_name", models.CharField(max_length=100)),
                (
                    "id_ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios",
                        to="arquivos.ata",
                    ),
                ),
            ],
        ),
    ]
